name: drmoovy
description: Mobile App for Moovy Autonomous Robot by Fablab Team. 
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # slider_button: ^0.6.0
  # flutter_thermometer: ^1.0.0
  # syncfusion_flutter_gauges: ^18.3.48


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/